# Site settings
title: Bits and pieces
description: "My personal (b)log regarding embedded software & systems."
baseurl: ""
url: ""
github_username:  renemoll

# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

paginate: 10
permalink: /:year/:month/:day/:title.html
sidebar_home_link: true
excerpt_separator: <!--more-->
