# Site settings
title: Bits and pieces
description: >- # this means to ignore newlines until "baseurl:"
  My personal (b)log regarding embedded software & systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  renemoll

# Build settings
markdown: kramdown
#theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 10
permalink: /:year/:month/:day/:title.html
sidebar_home_link: true
